### ISSUE TITLE
Make the timestamp name in nTimestomp the same as in nTimeview

### ISSUE THREAD

**Issue by ghost** [limbenjamin/nTimetools#3]
When nTimeview is used to get the timestamps it displays these timestamp names.

```
[M] Last Write Time:
[A] Last Access Time:
[C] Metadata Change Time:
[B] Creation Time:
```

When nTimestomp is used:

```
\nTimestomp_v1.1_x64.exe

Usage: .\nTimestomp.exe [Modified Date] [Last Access Date] [Last Write Date] [Creation Date]
Date Format: yyyy-mm-dd hh:mm:ss.ddddddd
```

Can you change it from `[Modified Date] [Last Access Date] [Last Write Date] [Creation Date]` ->> `[Last Write Time] [Last Access Time] [Metadata Change Time] [Creation Time]`? 

Why? Because of Windows documentation.
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfiletime

```
BOOL SetFileTime(
  HANDLE         hFile,
  const FILETIME *lpCreationTime,
  const FILETIME *lpLastAccessTime,
  const FILETIME *lpLastWriteTime
);
```

One question, where did you get the information for this timestamp name `Metadata Change Time`? Is there any documentation in Windows that shows it like that? I have not found anything on Microsoft website.

**Comment by limbenjamin** [comment]
Hi fillAl,

I have standardised the order of the arguments to be MACB.  Most forensics analysts out use this ordering.
[https://www.andreafortuna.org/2017/10/06/macb-times-in-windows-forensic-analysis/](https://www.andreafortuna.org/2017/10/06/macb-times-in-windows-forensic-analysis/)
[https://cyberforensicator.com/2017/08/16/windows-macb-timestamps-ntfs-forensics/](https://cyberforensicator.com/2017/08/16/windows-macb-timestamps-ntfs-forensics/)

As you brought up in #4  , I think it is a good suggestion and have added optional flags so it is possible to change only 1 or 2 timestamps.

Usage: .\nTimestomp.exe -F filename [-M Last Write Time] [-A Last Access Time] [-C Metadata Change Time] [-B Creation Time]


In order to change the metadata change time, you will need to go deeper into NTAPIs. I have covered it briefly in [https://limbenjamin.com/articles/timestomping-programmatically.html](https://limbenjamin.com/articles/timestomping-programmatically.html). 

The data structure used is [File Basic Information](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/16023025-8a78-492f-8b96-c873b042ac50)

**Comment by gitbbkload** [comment]
> In order to change the metadata change time, you will need to go deeper into NTAPIs. I have covered it briefly in https://limbenjamin.com/articles/timestomping-programmatically.html.
> 
> The data structure used is [File Basic Information](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/16023025-8a78-492f-8b96-c873b042ac50)

Hey thanks for the info. According to your blog and Microsoft site this name is used: `ChangeTime`. Maybe it should be changed from `Metadata Change Time` to `Change Time`.
